name: mesoflux-ml
channels:
  - conda-forge
dependencies:
  - python=3.12.8
  - pip=25.0.1
  - pyyaml=6.0.2
  - h5py=3.14.0
  - h5netcdf=1.6.4
  - pip:
      - cartopy==0.24.1
      - cftime==1.6.4.post1
      - matplotlib==3.10.0
      - netcdf4==1.7.2
      - numpy==2.1.3
      - optuna==4.2.0
      - pandas==2.2.3
      - pyproj==3.7.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - shap==0.46.0
      - shapely==2.0.7
      - threadpoolctl==3.5.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - xarray==2025.1.2